default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: accounting_development

test:
  <<: *default
  database: accounting_test

production:
  <<: *default
  database: accounting_production
  username: accounting
  password: <%= ENV["ACCOUNTING_DATABASE_PASSWORD"] %>
