default: &default
  adapter: postgresql
  encoding: unicode
  host: 0.0.0.0
  port: 5433
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: accounting_development

test:
  <<: *default
  database: accounting_test

production:
  <<: *default
  database: accounting_production
  username: <%= ENV["ACCOUNTING_DATABASE_USERNAME"] %>
  password: <%= ENV["ACCOUNTING_DATABASE_PASSWORD"] %>
