source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "devise"
gem "doorkeeper"
gem 'dry-monads'
gem 'activeadmin'
gem "tailwindcss-rails"
gem "events", path: "../../components/events"
gem "pry-rails"

# Default rails stuff
gem "rails", "~> 7.0.6"
gem "sprockets-rails"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "redis", "~> 4.0"
# gem "kredis"
# gem "bcrypt", "~> 3.1.7"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
gem "bootsnap", require: false
gem "sassc-rails"
# gem "image_processing", "~> 1.2"

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails'
end

group :development do
  gem "rubocop", require: false
  gem "web-console"
  # gem "rack-mini-profiler"
  # gem "spring"
end
