default: &default
  adapter: postgresql
  encoding: unicode
  host: 0.0.0.0
  port: 5433
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: auth_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: auth_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: auth_production
  username: auth
  password: <%= ENV["AUTH_DATABASE_PASSWORD"] %>
