default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: analytics_development

test:
  <<: *default
  database: analytics_test

production:
  <<: *default
  database: analytics_production
  username: accounting
  password: <%= ENV["ANALYTICS_DATABASE_PASSWORD"] %>
