default: &default
  adapter: postgresql
  encoding: unicode
  host: 0.0.0.0
  port: 5433
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task_tracker_development

test:
  <<: *default
  database: task_tracker_test

production:
  <<: *default
  database: task_tracker_production
  username: <%= ENV["TASK_TRACKER_DATABASE_USERNAME"] %>
  password: <%= ENV["TASK_TRACKER_DATABASE_PASSWORD"] %>
